apiVersion: v1
kind: Secret
metadata:
  name: crud-secret
type: Opaque
data:
  DB_HOST: Y3VyZGFwcC5jeWZxZnYwcjF2YzIudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_USER: YWRtaW4=
  DB_PASSWORD: bmRvcm9heXVkZXN0aWFla2E=
  AWS_ACCESS_KEY_ID: QVNJQVdIVUtNRk1ITERFVlVLTjM=
  AWS_SECRET_ACCESS_KEY: c0owc1poR2ZYOWZTZmVqT3VyOE1HSGJLUzNhNFBCT29IcVNkeWFsMQ==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVEc2FDWFZ6TFhkbGMzUXRNaUpITUVVQ0lRQ1hIOEk5QytNSHRoVEFqODIyTk1tTStodGlQa0ZUVER0eWI1dnBsVENuV0FJZ2FYUUNYdFE4bnJ0VUdTZUIvOVNlOVM5MlJTOExOdEJNTFJaakVuWjdZZUlxb3dJSUJCQUFHZ3cwTWpnM01UTXhPVEl5TURZaURFT0thOVRWaGhBNjdGc1U3aXFBQWwxYWpMd0NHUkRZQjZxdmRQa3hXalJ4YTZ4L0tsdHpCQUE1VWNYbXZDS2tTbGRSQk95UzJLM3VESUNlVVUyelYvR3VINTNOYWdDUkZsRWRkSSt1VFRta1VBVjRjT3VJWVl2TXNiVXVLdTkvTFRxa1VnNTZ4VlFDQytCL3hBNTVjYThRbVQyWTRnUXpTaXkxeFMwYlNZblV3MTdnNE92TWFEL3VaRUduTFNMZFBWMU1pajZ5WC9HMERhNnJxUHNmNThnL1pOYUJWTm1kSmZxYVBhUmRMZERlTkx2cmlROVhKOGhBZWFNbUR5SENWTVkwSkNHYzJ5TDJKN0dSV0d3WENjWHlzdS9Rb0NSakM2MTg4a1haSE1uNmYwaHVneitBSWp5QXVWVVlUQ3dNUzd1S1k2ejBhcmNaMEcyZXNQU3M4SStUUDV3NFMxMFd5WHYwQ0tscGJUQXdzNmoveUFZNm5RRU5pT09Memx6RGoyT2t5d1pPa0k4RWRWZTFDcmd2UnZiMjlSM2ZoYm1GVkpjdlFpNjU3aUlkN0haSjBEcjB0SlJlNTlaajlWNXoyQXhqWmlSMWhFNUtwRWpKd205Y0N6bE1RV3ZkSmJTa2d5WlFSbXpuS0xvUjFMcnVuLy84MmZvVjlhV3NvdlAweEZzRmVJTHVVNVhScmVzQklZaFlBZmNRTDMvdjNQSDBucTRkVzRreW1uWnpISUJVaUk0Z1Nhc2h0anljRHZWQUVvUGdYUzNk